version: '3'

services:
  frontend:
    image: $EKORPKIT_FRONTEND_DOCKER_IMAGE_NAME:latest
    container_name: $EKORPKIT_FRONTEND_DOCKER_CONTAINER_NAME
    env_file:
      - frontend/.env
    ports:
      - "$EKORPKIT_FRONTEND_HOST_PORT:$EKORPKIT_FRONTEND_DOCKER_PORT"
    volumes:
        - $HOST_WORKSPACE_ROOT:$EKORPKIT_WORKSPACE_ROOT
        - ${PWD}/frontend/${EKORPKIT_FRONTEND_APP_DIR}:${EKORPKIT_FRONTEND_APP_DIR}
  backend:
    image: $EKORPKIT_BACKEND_DOCKER_IMAGE_NAME:latest
    container_name: $EKORPKIT_BACKEND_DOCKER_CONTAINER_NAME
    env_file:
      - backend/.env
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - "$EKORPKIT_BACKEND_HOST_PORT:$EKORPKIT_BACKEND_DOCKER_PORT"
    volumes:
        - $HOST_WORKSPACE_ROOT:$EKORPKIT_WORKSPACE_ROOT
        - ${PWD}/backend/${EKORPKIT_BACKEND_APP_DIR}:${EKORPKIT_BACKEND_APP_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["7"]
              capabilities: [gpu]
networks:
  default:
    name: $EKORPKIT_APP_DOCKER_NETWORK
    external: true
