version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.frontend
      args:
        BUILD_FROM: $FRONTEND_BUILD_FROM
    image: $FRONTEND_DOCKER_IMAGE_NAME
    container_name: $FRONTEND_DOCKER_CONTAINER_NAME
    env_file:
      - $FRONTEND_ENV_FILE
    ports:
      - "$FRONTEND_HOST_PORT:$FRONTEND_DOCKER_PORT"
    volumes:
        # - $WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT
        - ${BUILD_PATH}/frontend/${FRONTEND_APP_DIR}:${FRONTEND_APP_DIR}
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.backend
      args:
        BUILD_FROM: $BACKEND_BUILD_FROM
    image: $BACKEND_DOCKER_IMAGE_NAME
    container_name: $BACKEND_DOCKER_CONTAINER_NAME
    env_file:
      - $BACKEND_ENV_FILE
    ipc: host
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - "$BACKEND_HOST_PORT:$BACKEND_DOCKER_PORT"
    volumes:
        # - $WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT
        - ${BUILD_PATH}/backend/${BACKEND_APP_DIR}:${BACKEND_APP_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    name: $APP_DOCKER_NETWORK
    external: true
